sphinx 3.4.1 requires alabaster
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx 3.4.1 requires alabaster<0.8,>=0.7, which is not installed.